[project]
name = "press_release_rag"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2",
  "streamlit",
  "faiss-cpu",
  "langchain>=0.2",
  "langchain-community>=0.2",
  "langchain-text-splitters>=0.2",
]

[tool.setuptools.packages.find]
where = ["src"]
